apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  destination:
    name: ''
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.7.0
    chart: kube-prometheus-stack
    helm:
      parameters:
        - name: prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues
          value: 'false'
        - name: prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues
          value: 'false'
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
