apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lumazer/kubernetes_cluster.git
    path: online-boutique
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 15
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 15m0s
